name: ci 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - run: git config user.name "GitHub Actions Bot"
    - run: git config user.email "<>"
    - run: git fetch
    - run: git checkout gh-pages
    - run: gem install yard
    - run: yardoc scripts
    - run: rm -rf docs
    - run: mv doc docs
    - run: git add .yardoc docs
    - run: git commit -m "update docs"
    - run: git push origin gh-pages
